# Generated by Django 4.2.5 on 2024-01-10 14:07

import Ora_innovation_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ora_innovation_app', '0002_user_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=200)),
                ('servicesImages', models.ImageField(default=None, null=True, upload_to=Ora_innovation_app.models.wrapper)),
                ('postName', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('cost', models.FloatField()),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ora_innovation_app.services')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
