# Generated by Django 4.2.5 on 2024-01-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ora_innovation_app', '0004_cart_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
