# Generated by Django 4.2.5 on 2024-01-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ora_innovation_app", "0007_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="deleveryDateTime",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="orders",
            name="pickupDateTime",
            field=models.TimeField(),
        ),
    ]
