# Generated by Django 4.2.5 on 2024-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Ora_innovation_app", "0008_alter_orders_deleverydatetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="location",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
